/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type CallbackMsg = {
  update_state_on_reward_claim: {
    prev_astro_balance: Uint128;
    [k: string]: unknown;
  };
} | {
  update_state_on_liquidity_addition_to_pool: {
    prev_lp_balance: Uint128;
    [k: string]: unknown;
  };
} | {
  withdraw_user_rewards_callback: {
    user_address: Addr;
    withdraw_lp_shares?: Uint128 | null;
    [k: string]: unknown;
  };
};
export type Uint128 = string;
export type Addr = string;
export interface Config {
  airdrop_contract_address: Addr;
  astro_incentive_amount?: Uint128 | null;
  astro_token_address: Addr;
  deposit_window: number;
  generator_contract?: Addr | null;
  init_timestamp: number;
  lockdrop_contract_address: Addr;
  lp_tokens_vesting_duration: number;
  owner: Addr;
  pool_info?: PoolInfo | null;
  withdrawal_window: number;
  [k: string]: unknown;
}
export interface PoolInfo {
  astro_ust_lp_token_address: Addr;
  astro_ust_pool_address: Addr;
  [k: string]: unknown;
}
export type Cw20HookMsg = {
  delegate_astro_tokens: {
    user_address: string;
    [k: string]: unknown;
  };
} | {
  increase_astro_incentives: {
    [k: string]: unknown;
  };
};
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  update_config: {
    new_config: UpdateConfigMsg;
    [k: string]: unknown;
  };
} | {
  deposit_ust: {
    [k: string]: unknown;
  };
} | {
  withdraw_ust: {
    amount: Uint128;
    [k: string]: unknown;
  };
} | {
  init_pool: {
    slippage?: Decimal | null;
    [k: string]: unknown;
  };
} | {
  stake_lp_tokens: {
    [k: string]: unknown;
  };
} | {
  claim_rewards: {
    withdraw_lp_shares?: Uint128 | null;
    [k: string]: unknown;
  };
} | {
  callback: CallbackMsg;
};
export type Binary = string;
export type Decimal = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
  [k: string]: unknown;
}
export interface UpdateConfigMsg {
  astro_ust_pair_address?: string | null;
  generator_contract?: string | null;
  owner?: string | null;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  airdrop_contract_address: string;
  astro_token_address: string;
  deposit_window: number;
  init_timestamp: number;
  lockdrop_contract_address: string;
  lp_tokens_vesting_duration: number;
  owner?: string | null;
  withdrawal_window: number;
  [k: string]: unknown;
}
export interface MigrateMsg {
  [k: string]: unknown;
}
export type QueryMsg = {
  config: {
    [k: string]: unknown;
  };
} | {
  state: {
    [k: string]: unknown;
  };
} | {
  user_info: {
    address: string;
    [k: string]: unknown;
  };
};
export interface State {
  generator_astro_per_share: Decimal;
  is_lp_staked: boolean;
  lp_shares_minted?: Uint128 | null;
  pool_init_timestamp: number;
  total_astro_delegated: Uint128;
  total_ust_delegated: Uint128;
  [k: string]: unknown;
}
export interface UserInfoResponse {
  astro_delegated: Uint128;
  astro_incentive_transferred: boolean;
  auction_incentive_amount?: Uint128 | null;
  claimable_generator_astro: Uint128;
  claimed_lp_shares: Uint128;
  generator_astro_debt: Uint128;
  lp_shares?: Uint128 | null;
  user_gen_astro_per_share: Decimal;
  ust_delegated: Uint128;
  ust_withdrawn: boolean;
  withdrawable_lp_shares?: Uint128 | null;
  [k: string]: unknown;
}
export interface UserInfo {
  astro_delegated: Uint128;
  astro_incentive_transferred: boolean;
  auction_incentive_amount?: Uint128 | null;
  claimed_lp_shares: Uint128;
  generator_astro_debt: Uint128;
  lp_shares?: Uint128 | null;
  user_gen_astro_per_share: Decimal;
  ust_delegated: Uint128;
  ust_withdrawn: boolean;
  [k: string]: unknown;
}